spring:
  datasource:
    url: jdbc:mysql://localhost:3306/reporting
    username: root
    password: aneelap
    driver-class-name: com.mysql.cj.jdbc.Driver
    
  jpa:
    hibernate:
      ddl-auto: update
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    
